root = "."
testdata_dir = "testdata"
tmp_dir = ".devbox/bin/svc"

[build]
args_bin = []
bin = ";export $(grep -v '^#' ./.env.localhost | xargs); .devbox/bin/svc/server"
cmd = "go build -o .devbox/bin/svc/server cmd/server/main.go"
delay = 1000
exclude_dir = []
exclude_file = ["package.json", "package-lock.json", "project.json"]
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd/server", "pkg", "internal"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "svc/server/build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
