version: "0.5"
log_configuration:
    no_metadata: false
    rotation:
        max_size_mb: 1
        max_age_days: 3
        max_backups: 3
processes:
    server:
        command: air
        depends_on:
            postgresql:
                condition: process_healthy
        log_location: .devbox/logs/server.log
        readiness_probe:
            failure_threshold: 5
            http_get:
                host: localhost
                path: /
                port: 8080
                scheme: http
            initial_delay_seconds: 5
            period_seconds: 10
            success_threshold: 1
            timeout_seconds: 5
        shutdown:
            timeout_seconds: 10
    web:
        command: cd web && pnpm dev
        depends_on:
            server:
                condition: process_healthy
        log_location: .devbox/logs/web.log
        shutdown:
            timeout_seconds: 10
